name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: $psversiontable
      - run: pwsh -noninteractive Get-Module -listavailable
      - run: python3 --version
