name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: pwsh -command Set-PSRepository -name PSGallery -InstallationPolicy "Trusted"
      - run: pwsh -command Install-Module -Name Az
